# Análisis de las fuentes de información empleando EDA

In [24]:
import pandas as pd
import glob

In [56]:
from dataprep.eda import plot, plot_correlation, plot_missing, create_report

Paso 1: Lectura de archivo de referencia

In [74]:
ruta_datos = "D:/Datos/Limpios"
ruta_reporte ="D:/Datos/reporte/unificado"
ruta_referencia = f"{ruta_datos}/base_datos.Altavista"
df_referencia = pd.read_csv(ruta_referencia)
ruta_procesados="D:/Datos/Procesados"

In [20]:
df_referencia

,Altavista.comuna,Altavista.sexo_,Altavista.edad_,Altavista.fiebre,Altavista.cefalea,Altavista.dolrretroo,Altavista.malgias,Altavista.artralgia,Altavista.erupcionr,Altavista.dolor_abdo,...,Altavista.hem_mucosa,Altavista.hipotermia,Altavista.aum_hemato,Altavista.caida_plaq,Altavista.acum_liquievento,Altavista.extravasac,Altavista.hemorr_hem,Altavista.choque,Altavista.daño_orga,Altavista.clas_dengue
0,Altavista,F,1,1,1,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,1
1,Altavista,F,1,1,1,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,1
2,Altavista,F,0,1,1,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,1
3,Altavista,F,0,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,1
4,Altavista,F,0,1,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
677,Altavista,F,1,1,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
678,Altavista,M,0,1,1,1,1,1,0,1,...,0,0,0,1,0,0,0,0,0,0
679,Altavista,M,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
680,Altavista,F,0,1,1,0,1,1,0,0,...,0,0,0,0,1,1,0,2,0,3
681,Altavista,F,0,1,0,0,1,1,0,1,...,1,0,1,1,0,0,1,2,0,3

Paso 2: ajuste_columnas

In [21]:
columnas_originales = df_referencia.columns.values

In [32]:
columnas_nuevas = {columna: columna.split(".")[-1] for columna in columnas_originales}

In [33]:
columnas_nuevas

{'Altavista.comuna': 'comuna',
 'Altavista.sexo_': 'sexo_',
 'Altavista.edad_': 'edad_',
 'Altavista.fiebre': 'fiebre',
 'Altavista.cefalea': 'cefalea',
 'Altavista.dolrretroo': 'dolrretroo',
 'Altavista.malgias': 'malgias',
 'Altavista.artralgia': 'artralgia',
 'Altavista.erupcionr': 'erupcionr',
 'Altavista.dolor_abdo': 'dolor_abdo',
 'Altavista.vomito': 'vomito',
 'Altavista.somnolenci': 'somnolenci',
 'Altavista.hipotensio': 'hipotensio',
 'Altavista.hepatomeg': 'hepatomeg',
 'Altavista.hem_mucosa': 'hem_mucosa',
 'Altavista.hipotermia': 'hipotermia',
 'Altavista.aum_hemato': 'aum_hemato',
 'Altavista.caida_plaq': 'caida_plaq',
 'Altavista.acum_liquievento': 'acum_liquievento',
 'Altavista.extravasac': 'extravasac',
 'Altavista.hemorr_hem': 'hemorr_hem',
 'Altavista.choque': 'choque',
 'Altavista.daño_orga': 'daño_orga',
 'Altavista.clas_dengue': 'clas_dengue'}

In [34]:
df_referencia.rename(columns=columnas_nuevas,inplace=True)

In [35]:
df_referencia

,comuna,sexo_,edad_,fiebre,cefalea,dolrretroo,malgias,artralgia,erupcionr,dolor_abdo,...,hem_mucosa,hipotermia,aum_hemato,caida_plaq,acum_liquievento,extravasac,hemorr_hem,choque,daño_orga,clas_dengue
0,Altavista,F,1,1,1,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,1
1,Altavista,F,1,1,1,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,1
2,Altavista,F,0,1,1,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,1
3,Altavista,F,0,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,1
4,Altavista,F,0,1,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
677,Altavista,F,1,1,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
678,Altavista,M,0,1,1,1,1,1,0,1,...,0,0,0,1,0,0,0,0,0,0
679,Altavista,M,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
680,Altavista,F,0,1,1,0,1,1,0,0,...,0,0,0,0,1,1,0,2,0,3
681,Altavista,F,0,1,0,0,1,1,0,1,...,1,0,1,1,0,0,1,2,0,3

In [49]:
def renombrar_df(df: pd.DataFrame):
    columnas_originales = df.columns.values
    columnas_nuevas = {columna: columna.split(".")[-1] for columna in columnas_originales}
    #print(columnas_nuevas)
    return df.rename(columns=columnas_nuevas)

In [53]:
columnas_nuevas

{'Altavista.comuna': 'comuna',
 'Altavista.sexo_': 'sexo_',
 'Altavista.edad_': 'edad_',
 'Altavista.fiebre': 'fiebre',
 'Altavista.cefalea': 'cefalea',
 'Altavista.dolrretroo': 'dolrretroo',
 'Altavista.malgias': 'malgias',
 'Altavista.artralgia': 'artralgia',
 'Altavista.erupcionr': 'erupcionr',
 'Altavista.dolor_abdo': 'dolor_abdo',
 'Altavista.vomito': 'vomito',
 'Altavista.somnolenci': 'somnolenci',
 'Altavista.hipotensio': 'hipotensio',
 'Altavista.hepatomeg': 'hepatomeg',
 'Altavista.hem_mucosa': 'hem_mucosa',
 'Altavista.hipotermia': 'hipotermia',
 'Altavista.aum_hemato': 'aum_hemato',
 'Altavista.caida_plaq': 'caida_plaq',
 'Altavista.acum_liquievento': 'acum_liquievento',
 'Altavista.extravasac': 'extravasac',
 'Altavista.hemorr_hem': 'hemorr_hem',
 'Altavista.choque': 'choque',
 'Altavista.daño_orga': 'daño_orga',
 'Altavista.clas_dengue': 'clas_dengue'}

In [54]:
rutas_archivos = glob.glob(f"{ruta_datos}/*")
df_concatenado = pd.DataFrame(columns= columnas_nuevas.values())
for ruta in rutas_archivos:
    df_temporal = pd.read_csv(ruta)
    df_temporal = renombrar_df(df_temporal)
    #print(df_temporal.columns.values)
    df_concatenado = pd.concat([df_concatenado,df_temporal],axis=0)

In [67]:
df_concatenado = df_concatenado.infer_objects()
df_concatenado["comuna"] = df_concatenado["comuna"].astype("category")
df_concatenado["sexo_"] = df_concatenado["sexo_"].astype("category")

In [69]:
df_concatenado.dtypes

comuna              category
sexo_               category
edad_                  int64
fiebre                 int64
cefalea                int64
dolrretroo             int64
malgias                int64
artralgia              int64
erupcionr              int64
dolor_abdo             int64
vomito                 int64
somnolenci             int64
hipotensio             int64
hepatomeg              int64
hem_mucosa             int64
hipotermia             int64
aum_hemato             int64
caida_plaq             int64
acum_liquievento       int64
extravasac             int64
hemorr_hem             int64
choque                 int64
daño_orga              int64
clas_dengue            int64
dtype: object

Paso 3: Crear reporte generico de datos

In [73]:
reporte_calidad = create_report(df_concatenado)
reporte_calidad.save(ruta_reporte)

  0%|          | 0/2123 [00:00<?, ?it/s]

Report has been saved to D:\Datos\reporte\unificado.html!

Paso 4: guardar en diferentes archivos en base a la comuna

In [76]:
grupos = df_concatenado.groupby("comuna")
for grupo in grupos.groups:
    grupos.get_group(grupo).to_csv(f"{ruta_procesados}/{grupo}.csv" ,index=False)